#!/usr/bin/env python
"""Regenerate the machine-readable context files from the code itself.

Agents work better with a factual map than with prose that drifts. This script walks
the live app and prints:

  * every route: rule, methods, endpoint, and which auth decorator guards it
  * every model: table name, columns, types, nullability, foreign keys, indexes
  * every setting the admin can change, with its current value and label
  * every environment variable the app reads, with its default

Usage (inside the container, so it sees the real app and its database):

    docker compose exec -T web python /app/scripts/build_agent_docs.py --out /tmp/docs
    docker cp btcwallet-web:/tmp/docs/context.md docs/generated/context.md

Copy the app stylesheet next to the demo page in the same run (they must not drift):

    ... --sync-demo-assets
    docker cp btcwallet-web:/tmp/docs/assets/app.css docs/assets/app.css

The concatenated single-file corpus needs neither a database nor the app imports, so it
can be produced on any checkout — including CI:

    python scripts/build_agent_docs.py --llms-full llms-full.txt
"""

import argparse
import inspect
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)

# Order matters: the index first, then the docs it points at, so a reader (or a model)
# gets the map before the detail.
FULL_TEXT_FILES = (
    "llms.txt", "README.md", "docs/architecture.md", "docs/data-model.md",
    "docs/security.md", "docs/operations.md", "docs/demo.md",
    "docs/generated/context.md", "SECURITY.md",
)


def llms_full(repo_root):
    """Concatenate the documentation into one file for models that take a single blob."""
    parts = []
    for rel in FULL_TEXT_FILES:
        path = os.path.join(repo_root, rel)
        if not os.path.exists(path):
            print(f"  (skipped, not present: {rel})", file=sys.stderr)
            continue
        body = open(path, encoding="utf-8").read().strip()
        parts.append(f"\n\n{'=' * 78}\n# FILE: {rel}\n{'=' * 78}\n\n{body}")
    header = ("<SYSTEM>\nBTC Vault — concatenated documentation. Generated by\n"
              "scripts/build_agent_docs.py from the files named below; each section is one\n"
              "repository file, in the order llms.txt lists them.\n</SYSTEM>")
    return header + "".join(parts) + "\n"


# ------------------------------------------------------------------ app walkers
def _guard_of(view_func):
    """Which decorator gates this view? Read it off the wrapped function."""
    try:
        src = inspect.getsource(view_func)
    except (OSError, TypeError):
        return "?"
    for name in ("admin_required", "active_required", "login_required", "sudo_required"):
        if f"@{name}" in src or f" {name}(" in src:
            return name
    return "public"


def routes_section(app):
    lines = ["## Routes", "", "| Rule | Methods | Endpoint | Guard |", "|---|---|---|---|"]
    for rule in sorted(app.url_map.iter_rules(), key=lambda r: (str(r.rule), r.endpoint)):
        if rule.endpoint == "static":
            continue
        view = app.view_functions.get(rule.endpoint)
        guard = _guard_of(inspect.unwrap(view)) if view is not None else "static"
        methods = ",".join(sorted(m for m in rule.methods if m not in ("HEAD", "OPTIONS")))
        lines.append(f"| `{rule.rule}` | {methods} | `{rule.endpoint}` | {guard} |")
    lines.append("")
    return lines


def models_section():
    from app.extensions import db
    from app import models  # noqa: F401  (registers metadata)

    lines = ["## Tables", ""]
    for table in sorted(db.metadata.sorted_tables, key=lambda t: t.name):
        lines += [f"### `{table.name}`", "",
                  "| Column | Type | Null | Default |", "|---|---|---|---|"]
        for col in table.columns:
            fks = ", ".join(f"{fk.column.table.name}.{fk.column.name}"
                            for fk in col.foreign_keys)
            typ = str(col.type) + (f" → {fks}" if fks else "")
            default = "" if col.default is None else str(col.default.arg)
            lines.append(f"| `{col.name}` | {typ} | {'no' if not col.nullable else 'yes'} "
                         f"| {default} |")
        for ix in table.indexes:
            lines.append(f"- index `{ix.name}` on "
                         f"({', '.join(c.name for c in ix.columns)})")
        for con in table.constraints:
            if type(con).__name__ == "UniqueConstraint":
                lines.append(f"- unique `{con.name}` on "
                             f"({', '.join(c.name for c in con.columns)})")
        lines.append("")
    return lines


def settings_section():
    from app import services

    lines = ["## Admin-editable settings", "", "| Key | Current value | Label |", "|---|---|---|"]
    for key, (label, _help) in services.SETTING_LABELS.items():
        try:
            value = services.get_setting(key)
        except Exception:
            value = "(unavailable)"
        lines.append(f"| `{key}` | `{value}` | {label} |")
    lines += ["", f"Network: `{services.network().name}`", ""]
    return lines


REDACT = (
    # A default that names this deployment's own host is not a secret, but it does not
    # belong in a generated public doc either. Replace the host part, keep the shape.
    (re.compile(r"\b\d{1,3}(?:[-.]\d{1,3}){3}\b"), "<your-ip>"),
    (re.compile(r"\b[a-z0-9-]+\.sslip\.io\b", re.I), "<your-host>"),
)


def _redact(value):
    for pattern, replacement in REDACT:
        value = pattern.sub(replacement, value)
    return value


def env_section(root_app):
    """Every os.environ lookup in the app, with the default it falls back to."""
    found = {}
    pattern = re.compile(
        r"os\.environ(?:\.get)?\(?\[?[\"']([A-Z0-9_]+)[\"']\]?[^)]*?[\"']([^\"']*)[\"']"
    )
    for base, _dirs, files in os.walk(root_app):
        for name in files:
            if not name.endswith(".py"):
                continue
            text = open(os.path.join(base, name), encoding="utf-8").read()
            for var, default in pattern.findall(text):
                found.setdefault(var, default)
            for var in re.findall(r"os\.environ\[\s*[\"']([A-Z0-9_]+)[\"']", text):
                found.setdefault(var, "(required)")
    lines = ["## Environment variables", "", "| Variable | Fallback default in code |", "|---|---|"]
    for var in sorted(found):
        lines.append(f"| `{var}` | `{_redact(found[var])}` |")
    lines.append("")
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="directory to write context.md into")
    ap.add_argument("--stdout", action="store_true", help="print the context to stdout")
    ap.add_argument("--sync-demo-assets", action="store_true",
                    help="also copy app/static/css/app.css and js/app.js for the demo page")
    ap.add_argument("--llms-full", metavar="PATH",
                    help="write the concatenated llms-full.txt to PATH (no app needed)")
    ap.add_argument("--repo-root", default=REPO_ROOT,
                    help="repository root used for --llms-full (default: parent of scripts/)")
    args = ap.parse_args()

    if args.llms_full:
        full = llms_full(args.repo_root)
        with open(args.llms_full, "w", encoding="utf-8") as fh:
            fh.write(full)
        print(f"wrote {args.llms_full} ({len(full)} bytes)", file=sys.stderr)
        if not (args.out or args.stdout):
            return 0

    # the app walkers need the real app (and a database for the settings section)
    sys.path.insert(0, REPO_ROOT)
    from app import create_app
    from app.config import Config

    app = create_app(Config)
    out = ["# Generated context", "",
           "Regenerate with `python scripts/build_agent_docs.py`. Do not edit by hand —",
           "this file is a snapshot of the code at the moment it was generated.", ""]
    out += routes_section(app)
    with app.app_context():
        # db.metadata and the settings table both need an application context
        out += models_section()
        out += settings_section()
    out += env_section("/app/app")
    text = "\n".join(out)

    if args.stdout or not args.out:
        print(text)
    if args.out:
        os.makedirs(args.out, exist_ok=True)
        path = os.path.join(args.out, "context.md")
        open(path, "w", encoding="utf-8").write(text)
        print(f"wrote {path} ({len(text)} bytes)", file=sys.stderr)
        if args.sync_demo_assets:
            demo_assets = os.path.join(args.out, "assets")
            os.makedirs(demo_assets, exist_ok=True)
            for src, name in (("/app/app/static/css/app.css", "app.css"),
                              ("/app/app/static/js/app.js", "app.js")):
                shutil.copyfile(src, os.path.join(demo_assets, name))
                print(f"copied {name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
